<h1>Numpy Boi!!!!</h1>

In [3]:
import numpy as np

In [2]:
import tensorflow as tf
print(tf.__version__)

2023-05-18 09:09:00.459713: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-18 09:09:00.812560: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-18 09:09:00.822055: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-18 09:09:02.586032: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


2.12.0


In [6]:
my_array = np.array([10,12,14,16,20,25])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

[10 12 14 16 20 25]
int64
8


In [7]:
strings_array = np.array(["Red", "Green", 'Orange'])
print(strings_array)
print(strings_array.dtype)
print(strings_array.dtype.itemsize)

['Red' 'Green' 'Orange']
<U6
24


In [8]:
dates_array = np.array(["1990-10-04", "1989-05-06", "1990-11-04"])
print(dates_array)
print(dates_array.dtype)
print(dates_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
<U10
40


In [10]:
proper_dates_array = dates_array.astype("M")
print(proper_dates_array)
print(proper_dates_array.dtype)
print(proper_dates_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
datetime64[D]
8


In [11]:
predefined_datetime = np.array(["1990-10-04", "1990-10-05", "1990-10-06", "1990-10-07"],  dtype=np.datetime64)

print(predefined_datetime)
print(predefined_datetime.dtype)
print(predefined_datetime.dtype.itemsize)

['1990-10-04' '1990-10-05' '1990-10-06' '1990-10-07']
datetime64[D]
8


In [12]:
nums_list = [10,12,14,16,20]
nums_array = np.array(nums_list)
type(nums_array)

numpy.ndarray

In [13]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [2,3,4]

nums_2d = np.array([row1,row2,row3])
nums_2d.shape

(3, 3)

In [15]:
nums = np.arange(5,11)
print(nums)

[ 5  6  7  8  9 10]


In [16]:
nums_2 = np.arange(5,11,2)
print(nums_2)

[5 7 9]


In [17]:
num_ones = np.ones(6)
print(num_ones)

[1. 1. 1. 1. 1. 1.]


<p>A bunch of random numbers with uniform distribution</p>

In [27]:
uniform_random = np.random.rand(4,5)
print(uniform_random)

[[0.56168583 0.79888642 0.21936402 0.5530308  0.20102644]
 [0.54626212 0.25261165 0.16338875 0.79234289 0.80955967]
 [0.6129445  0.12352328 0.74075768 0.07973316 0.86727606]
 [0.78763185 0.89488529 0.71429571 0.40693475 0.59362954]]


<p>Numbers with a normal distribution</p>

In [20]:
normal_random = np.random.randn(4,5)
print(normal_random)

[[ 1.25089304  0.26540633  0.58826603 -0.51280678 -0.52504578]
 [ 2.01673263 -0.44888395 -0.15462405 -0.07774187 -0.6450154 ]
 [ 0.06938973 -0.63403504  2.35959277 -0.46280415 -0.41295903]
 [-0.42680964 -1.19585864  1.66534235  0.19525684  1.22741604]]


<p>Generate a bunch of random integers</p>

In [21]:
integer_random = np.random.randint(10, 50, 5)
print(integer_random)

[45 41 36 15 49]


In [24]:
print(integer_random.ndim)

1


In [30]:
print(uniform_random.ndim)
print(uniform_random.shape)

2
(4, 5)


In [33]:
colors_array = np.array(["Red", "Green", "Blue"])
print(colors_array)
updated_colors_array = np.append(colors_array, "Orange")
print(updated_colors_array)

['Red' 'Green' 'Blue']
['Red' 'Green' 'Blue' 'Orange']


<h2>Numpy Array Manipulation<h2>

In [36]:
print("Unsorted Array")
rand_int_array = np.random.randint(1,20,10)
print(rand_int_array)
print("/n")
print("Sorted Array")
sorted_int_array = np.sort(rand_int_array)
print(sorted_int_array)

Unsorted Array
[15 11  2 16 11  9 12  3 12  5]
/n
Sorted Array
[ 2  3  5  9 11 11 12 12 15 16]


In [38]:
print("Random unsorted colors array")
random_colors_array = np.array(["Red", "Green", "Blue", "Yellow"])
print(random_colors_array)
print("Sorted colors array")
sorted_colors_array = np.sort(random_colors_array)
print(sorted_colors_array)

Random unsorted colors array
['Red' 'Green' 'Blue' 'Yellow']
Sorted colors array
['Blue' 'Green' 'Red' 'Yellow']


<p>Array Reshaping</p>

In [39]:
print("One dimensional array")
one_d_array = np.random.randint(1, 20, 10)
print(one_d_array)

print("Two dimensional array")
two_d_array = one_d_array.reshape(2, 5)
print(two_d_array)

One dimensional array
[19  7  8  3  7  1 16 10  6 13]
Two dimensional array
[[19  7  8  3  7]
 [ 1 16 10  6 13]]


<p>Higher Order Array Reshaping</p>

In [40]:
print("Two dimensional array")
two_d_array = np.random.randint(1, 20, size=(4, 6))
print(two_d_array)

print("Three dimensional array")
three_d_array = np.reshape(two_d_array, (3,4,2))
print(three_d_array)

Two dimensional array
[[13  4  6 19 16 19]
 [ 5  1 16 12  9  8]
 [ 4  8  2  8  2 17]
 [ 5 11 10  8  4 12]]
Three dimensional array
[[[13  4]
  [ 6 19]
  [16 19]
  [ 5  1]]

 [[16 12]
  [ 9  8]
  [ 4  8]
  [ 2  8]]

 [[ 2 17]
  [ 5 11]
  [10  8]
  [ 4 12]]]


In [41]:
print("Two dimensional array")
two_d_array = np.random.randint(0, 10, (4, 6))
print(two_d_array)

print("One dimensional array")
one_d_array = two_d_array.reshape(-1)
print(one_d_array)

Two dimensional array
[[6 7 9 8 1 9]
 [5 7 5 5 1 4]
 [8 0 0 4 7 8]
 [4 1 3 0 1 9]]
One dimensional array
[6 7 9 8 1 9 5 7 5 5 1 4 8 0 0 4 7 8 4 1 3 0 1 9]


In [44]:
s = np.arange(1, 11)
print(s)
# Array indexed
print(s[1])
# Array slice
print(s[2:5])

[ 1  2  3  4  5  6  7  8  9 10]
2
[3 4 5]


<p>Simple Broadcasting Example</p>

In [45]:
array1 = np.random.randint(1, 20, (3, 4))
print(array1)

array2 = np.array([[5], [10], [20]])
print(array2)

print("After Broadcasting")

result = array1 + array2
print(result)

[[ 2 18 10  6]
 [12  8  1 12]
 [ 6  4 18  7]]
[[ 5]
 [10]
 [20]]
After Broadcasting
[[ 7 23 15 11]
 [22 18 11 22]
 [26 24 38 27]]


<p>Copying Numpy Arrays</p>

In [46]:
array1 = np.array([10, 12, 14, 16, 18, 20])
array2 = array1.copy()
array2[1] = 20

print(array1)
print(array2)

[10 12 14 16 18 20]
[10 20 14 16 18 20]


<p>I/O Operations</p>

In [47]:
np.save("./my_array", array1)

In [48]:
saved_array = np.load("./my_array.npy")
print(saved_array)

[10 12 14 16 18 20]


<h2>Statistical Operations</h2>

<p>Mean</p>

In [49]:
my_array = np.array([2,4,6,8,10,12])
print(my_array)
print("Mean: ")
print(np.mean(my_array))

[ 2  4  6  8 10 12]
Mean: 
7.0


<p>Two dimensional mean</p>

In [50]:
two_d_array = np.random.randint(1, 20, (2,3))
print(two_d_array)
print("Mean: ")
print(np.mean(two_d_array, axis=1))
print(np.mean(two_d_array, axis=0))

[[ 3 15  9]
 [ 7 10  3]]
Mean: 
[9.         6.66666667]
[ 5.  12.5  6. ]


<p>Median</p>

In [51]:
print(np.median(my_array))

7.0


<p>Two dimension median</p>

In [52]:
print(np.median(two_d_array, axis=1))
print(np.median(two_d_array, axis=0))

[9. 7.]
[ 5.  12.5  6. ]


<p>Min and Max values in an array</p>

In [53]:
print("Array Min")
print(np.amin(my_array))
print("Array Max")
print(np.amax(my_array))

Array Min
2
Array Max
12


<p>Min and Max values for two dimensions</p>

In [55]:
print("Min 0")
print(np.amin(two_d_array, axis=1))
print("Max 0")
print(np.amax(two_d_array, axis=1))
print("Min 1")
print(np.amin(two_d_array, axis=0))
print("Max 1")
print(np.amax(two_d_array, axis=0))

Min 0
[3 3]
Max 0
[15 10]
Min 1
[ 3 10  3]
Max 1
[ 7 15  9]


<p>The standard deviation of a numpy array</p>

In [56]:
print("Std deviation")
print(np.std(my_array))

Std deviation
3.415650255319866


<p>The standard deviation in a two dimensional array</p>

In [58]:
my_array =np.random.randint(1, 100, (3, 4))
print(my_array)
print("Std deviation")
print(np.std(my_array, axis=1))
print(np.std(my_array, axis=0))

[[25 20 39 15]
 [83 91 10 60]
 [21 74 65 20]]
Std deviation
[ 8.95474734 31.56738824 24.7082982 ]
[28.33137248 30.26916289 22.46478726 20.13840996]


<p>Correlation</p>

In [60]:
a1 = np.array([1,3,0,0.9,1.2])
a2 = np.array([-1, 0.5, 0.2, 0.6, 5])
print(a1)
print(a2)
print("Correlation Value")
print(np.correlate(a1, a2))

[1.  3.  0.  0.9 1.2]
[-1.   0.5  0.2  0.6  5. ]
Correlation Value
[7.04]


<p>Unique Items and Counts</p>

In [64]:
my_array = np.array([ 5 , 8 , 7 , 5 , 9 , 3 , 7 , 7 , 1 , 1 , 8 , 4 , 6 , 9 , 7 , 3 ])

unique_items, counts = np.unique(my_array, return_counts=True)

print("Unique Items")
print(unique_items)
print("Counts")
print(counts)

Unique Items
[1 3 4 5 6 7 8 9]
Counts
[2 2 1 2 1 4 2 2]


<p>Frequencies</p>

In [65]:
frequencies = np.asarray((unique_items, counts))
print(frequencies)

[[1 3 4 5 6 7 8 9]
 [2 2 1 2 1 4 2 2]]


In [66]:
frequencies = np.asarray((unique_items, counts)).T
print(frequencies)

[[1 2]
 [3 2]
 [4 1]
 [5 2]
 [6 1]
 [7 4]
 [8 2]
 [9 2]]
