<h1>Numpy Boi!!!!</h1>

In [3]:
import numpy as np

In [2]:
import tensorflow as tf
print(tf.__version__)

2023-05-18 09:09:00.459713: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-18 09:09:00.812560: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-18 09:09:00.822055: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-18 09:09:02.586032: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


2.12.0


In [6]:
my_array = np.array([10,12,14,16,20,25])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

[10 12 14 16 20 25]
int64
8


In [7]:
strings_array = np.array(["Red", "Green", 'Orange'])
print(strings_array)
print(strings_array.dtype)
print(strings_array.dtype.itemsize)

['Red' 'Green' 'Orange']
<U6
24


In [8]:
dates_array = np.array(["1990-10-04", "1989-05-06", "1990-11-04"])
print(dates_array)
print(dates_array.dtype)
print(dates_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
<U10
40


In [10]:
proper_dates_array = dates_array.astype("M")
print(proper_dates_array)
print(proper_dates_array.dtype)
print(proper_dates_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
datetime64[D]
8


In [11]:
predefined_datetime = np.array(["1990-10-04", "1990-10-05", "1990-10-06", "1990-10-07"],  dtype=np.datetime64)

print(predefined_datetime)
print(predefined_datetime.dtype)
print(predefined_datetime.dtype.itemsize)

['1990-10-04' '1990-10-05' '1990-10-06' '1990-10-07']
datetime64[D]
8


In [12]:
nums_list = [10,12,14,16,20]
nums_array = np.array(nums_list)
type(nums_array)

numpy.ndarray

In [13]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [2,3,4]

nums_2d = np.array([row1,row2,row3])
nums_2d.shape

(3, 3)

In [15]:
nums = np.arange(5,11)
print(nums)

[ 5  6  7  8  9 10]


In [16]:
nums_2 = np.arange(5,11,2)
print(nums_2)

[5 7 9]


In [17]:
num_ones = np.ones(6)
print(num_ones)

[1. 1. 1. 1. 1. 1.]


<p>A bunch of random numbers with uniform distribution</p>

In [19]:
uniform_random = np.random.rand(4,5)
print(uniform_random)

[[0.75573842 0.14767278 0.33948614 0.28522155 0.97958843]
 [0.80578496 0.07977822 0.61782959 0.08446693 0.02799271]
 [0.23758159 0.43782185 0.15565288 0.18496744 0.30249803]
 [0.0441112  0.02113254 0.91245304 0.7634611  0.5650233 ]]
